 <?php 
	echo V('form_error', array('form'=>$this->form));
?>
<div>
<label>您当前职位对应的ISO文件以及公司制度文件为</label><br><br>
<table width="80%" frame="hsides">
<tr ><td align="center">文件名称</td><td align="center">更新时间</td><td align="center">文件大小</td><td align="center">操作</td></tr>
		<?php
			$i = 0;
			foreach ($this->file as $key => $value) {
				$i++;
				if ($i%2) {
					$class = 'tdclass1';
				}else{
					$class = 'tdclass2';
				}
				echo '<tr class = "'.$class.'" >';
				echo '<td align="left" class="filename"><a href="'.URI::url('files/download').'.'.$value['fileno'].'.files">'.$value['filename'].'</a></td>';
				echo '<td align="center">'.$value['mtime'].'</td>';
				echo '<td align="center">'.$value['filesize'].'</td>';
				echo '<td align="center"><a class="button view" href="'.URI::url('files/download').'.'.$value['fileno'].'">下载</a></td></tr>';
			}
			
		?>
		
</table>
<?php 
	echo $this->pagination;
?>
</div>