 <?php 
echo V('form_error', array('form'=>$form));
?>
<div >
	
	<form method="post" autocomplete="off" action="<?php echo URI::url('login')?>">
	<table style="margin:auto" height="90px">
		<tbody>
			<tr>
				<td><label>帐号</label></td>
				<td colspan="2"><input name="token" type="text" class="text" size="30" tabindex="1"/>
				</td>
			</tr>
			<tr>
				<td >密码</td>
				<td colspan="2">
					<input name="password" type="password" size="30" tabindex="2"/>
				</td>
			</tr>
			<tr>
				<td></td>
				<td>
					<input type="submit" name="submit" value="登陆" tabindex="4" />
				</td>
			</tr>
		</tbody>
	</table>
	</form>
</div>