<?php
	echo V('form_error', array('form'=>$form));
?>
<div>
	<form action="<?php echo URI::url('personal/password')?>" method="post">
	<table width="100%" height='100px'>
		<tr ><td align="right"><label for="oldpwd" >原密码：</label></td><td align="left"><input type="password" name="oldpwd"></td></tr>
		<tr align="center"><td align="right"><label for="newpwd" >新密码：</label></td><td align="left"><input type="password" name="newpwd"><label class='hint'>(密码长度不得少于6位)</label></td></tr>
		<tr ><td align="right"><label for="confirm" >重复密码：</label></td><td align="left"><input type="password" name="confirm"><label class='hint'>(密码长度不得少于6位)</label></td></tr>
		<tr ><td align="right"></td><td align="left"><input type="submit" name="modifypwd" value="确认提交">
			<input type="reset" name="resetpwd" value="重置修改"></td></tr>
	</table>
	</form>
</div>