<div>
<form method="POST" class="view" q-event="submit" q-object="signup" q-src="<?php echo URI::url('personal')?>">
	<table width="80%">
		<tr align="center">
			<td align="right"><label>用户名:</label></td><td align="left"><input type="text" name="token" class="text" size="30" tabindex="1"></td>
		</tr>
		<tr align="center">
			<td align="right"><label>用户姓名:</label></td>
				<td align="left"><input type="text" name="name" class="text" size="30" tabindex="2"></td>
		</tr>
		<tr align="center">
			<td align="right">
				<label>所在部门:</label>
			</td>
			<td align="left">
				<select id="apartment" name="apartment">  
  					<?php 
  						$apartment = $this->position;
  						if (is_array($apartment)) {
  							echo "<option value='0'></option>";
  							$i=0;
  							foreach ($apartment as $key => $value) {
  								echo "<option value=$key>$value</option>";
  								$i++;
  							}
  						}
  					?>
				</select>
				<label>职位:</label>
				<span class="position"></span>

			</td>
		</tr>
		<tr align="center">
			<td></td>
			<td align="left"><input type="submit" name="submit" value="提交注册">
			</td>
		</tr>
	</table>
</form>
</div>
 <script type="text/javascript">
 	(function($) {
    $sub_transaction_type_span = $('span.position');

    $transaction_type = $(':input[name=apartment]');


    sub_transaction_type = 0;

    //进行trigger
    function _trigger_change() {

        v = $transaction_type.val();

        if (v == 0) {
            $sub_transaction_type_span.empty(); //进行清空
        }
        else {

            Q.trigger({
                object: 'apartment_position',
                event: 'change',
                url: '<?php echo URI::url("personal")?>',
                data: {
                    transaction_type: v,
                    sub_transaction_type: sub_transaction_type
                },
                success: function(data) {
                   if (data.view_data) $sub_transaction_type_span.html(data.view_data); //如果有返回结果, 进行内容设定
                    return false;
                }
            });

            //进行trigger
            sub_transaction_type = 0;
        }

        return false;
    }

    _trigger_change(); 

    $transaction_type.bind('change', function() {
        _trigger_change();
    });

})(jQuery);
</script>